# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Product

# Model Form Field configuration
form: $/toomeowns/octoshoplite/models/product/fields.yaml

# Model Class name
modelClass: toomeowns\OctoshopLite\Models\Product

# Default redirect location
defaultRedirect: toomeowns/octoshoplite/products

# Create page
create:
    title: Create Product
    redirect: toomeowns/octoshoplite/products/update/:id
    redirectClose: toomeowns/octoshoplite/products

# Update page
update:
    title: Edit Product
    redirect: toomeowns/octoshoplite/products
    redirectClose: toomeowns/octoshoplite/products

# Preview page
preview:
    title: Preview Product
